version: '3'

services:
    traefik:
          image: "traefik:v2.4"
          container_name: "traefik_dev"
          restart: always
          command:
            - "--log.level=WARN"
            - "--log.format=json"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
          ports:
            - "80:80"
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        
    api:
        container_name: workshop_backend
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: "voiceworkshop2021/api-server"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
            - "traefik.http.routers.api.entrypoints=web"
            - "traefik.http.routers.api.service=api"
            - "traefik.http.services.api.loadbalancer.server.port=80"

