version: '3'

services:
    api:
        container_name: workshop_backend
        environment: 
            - "DANGEROUSLY_DISABLE_HOST_CHECK=true"
        build:
            context: ./api
            dockerfile: ./Dockerfile
        image: "voiceworkshop2021/api-server"
        ports:
            - "80:80"
        networks:
            - eth
    ui:
        container_name: workshop_frontend
        environment: 
            - "DANGEROUSLY_DISABLE_HOST_CHECK=true"
        build:
            context: ./ui
            dockerfile: ./Dockerfile
        image: "voiceworkshop2021/ui"
        networks:
            - eth
        ports:
            - "80:80"
networks: 
    eth:

